source 'http://rubygems.org'

gem 'activesupport'
gem 'capybara-screenshot'
gem 'capybara'
gem 'webdrivers', '~> 4.0'
gem 'cucumber'
gem 'poltergeist'
gem 'pry'
gem 'require_all'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'waitutil'
gem 'rake'
gem 'colorize'
